package concept.components.client;


import org.apache.http.impl.client.DefaultHttpClient;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import ac.simons.oembed.Oembed;
import ac.simons.oembed.OembedBuilder;
import ac.simons.oembed.OembedProvider;
import ac.simons.oembed.OembedProviderBuilder;
import ac.simons.oembed.OembedResponse;

import com.google.gdata.data.youtube.VideoEntry;
import com.webobjects.appserver.WOContext;

import concept.SWGenericComponent;
import concept.SWYouTubeUtils;
import concept.data.SWComponent;

public class SWYouTubePlayer extends SWGenericComponent {

	private static final Logger logger = LoggerFactory.getLogger( SWYouTubePlayer.class );

	public String videoId;
	public String embedHtml;
	public String videoTitle;
	public String videoDescription;

	public SWYouTubePlayer( WOContext context ) {
		super( context );
	}

	@Override
	public void setCurrentComponent( SWComponent theComponent ) {
		super.setCurrentComponent( theComponent );
		init();
	}

	/*
	 * Embed code generated by Google as of Aug 2012 is like so:
	 * <iframe width="560" height="315" src="http://www.youtube.com/embed/yC-63Dfhbf4?rel=0" frameborder="0" allowfullscreen></iframe>
	 */
	private void init() {
		embedHtml = "";
		videoTitle = "";
		videoDescription = "";

		videoId = customInfoString( "swyoutubeplayer_videoid", null );
		if( videoId == null ) {
			videoId = (String)context().request().formValueForKey( "videoid" );
		}

		if( videoId != null ) {
			String width = customInfoString( "swyoutubeplayer_width", null );
			String height = customInfoString( "swyoutubeplayer_height", null );
			VideoEntry video = SWYouTubeUtils.getVideoById( videoId );

			if( video != null ) {
				videoTitle = video.getTitle().getPlainText();
				videoDescription = video.getMediaGroup().getDescription().getPlainTextContent();

				if( width == null || height == null ) {
					// Get embed code from YouTube oembed service
					try {
						OembedProvider provider = new OembedProviderBuilder().withName( "youtube" ).withFormat( "json" ).withMaxWidth( width != null ? Integer.valueOf( width ) : 640 ).withEndpoint( "http://www.youtube.com/oembed" ).withUrlSchemes( "http://(www|de)\\.youtube\\.com/watch\\?v=.*" ).build();
						Oembed oembed = new OembedBuilder( new DefaultHttpClient() ).withProviders( provider ).build();
						String url = "http://www.youtube.com/watch?v=" + videoId;
						OembedResponse response = oembed.transformUrl( url );
						if( response != null ) {
							embedHtml = response.getHtml();
						}
						else {
							logger.info( "Got no Oembed response for url=" + url );
						}
					}
					catch( Exception ex ) {
						logger.error( "Exception while getting video embed code: ", ex );
					}
				}
				else {
					// Create embed code manually
					embedHtml = "<iframe width=\"" + width + "\" height=\"" + height + "\" src=\"http://www.youtube.com/embed/" + videoId + "\" frameborder=\"0\" allowfullscreen></iframe>";
				}
			}
			else {
				logger.info( "Unable to get info on videoid=" + videoId + " from YouTube" );
			}
		}
	}
}