package concept.logging;
import java.util.Date;
import java.util.Map;

import com.webobjects.foundation.NSTimestamp;

/**
 * A log message generated by an application.
 */

public class LogMessage {

	private Date _date;
	private Integer _timeToKeep;
	private String _applicationName;
	private String _type;
	private String _text;
	private String _userAgent;
	private String _softUserID;
	private Map<?,?> _info;

	public Date date() {
		return _date;
	}

	public void setDate( Date value ) {
		_date = value;
	}

	public Integer timeToKeep() {
		return _timeToKeep;
	}

	public void setTimeToKeep( Integer value ) {
		_timeToKeep = value;
	}

	public String applicationName() {
		return _applicationName;
	}

	public void setApplicationName( String value ) {
		_applicationName = value;
	}

	public String type() {
		return _type;
	}

	public void setType( String value ) {
		_type = value;
	}

	public String text() {
		return _text;
	}

	public void setText( String value ) {
		_text = value;
	}
	public Map<?,?> info() {
		return _info;
	}

	public void setInfo( Map<?,?> value ) {
		_info = value;
	}

	public String userAgent() {
		return _userAgent;
	}

	public void setUserAgent( String value ) {
		_userAgent = value;
	}

	public String softUserID() {
		return _softUserID;
	}

	public void setSoftUserID( String value ) {
		_softUserID = value;
	}

	public NSTimestamp timestamp() {
		if( date() != null ) {
			return new NSTimestamp( date() );
		}

		return null;
	}
	@Override
	public String toString() {
		return "LogMessage [_date=" + _date + ", _timeToKeep=" + _timeToKeep + ", _applicationName=" + _applicationName + ", _type=" + _type + ", _text=" + _text + ", _info=" + _info + "]";
	}
}